export const Popular = [
  {
    id: 1,
    title: "Avatar: The Way of Water",
    url: "https://www.rottentomatoes.com/m/avatar_the_way_of_water",
    img: "https://resizing.flixster.com/n2hcnjB7kowhKgEBV8-TeBeL6Js=/fit-in/180x240/v2/https://resizing.flixster.com/gWWM2Ov0VLAuazwELZCVc9grUQI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzgyMGM0ZDJiLWNmYjAtNGI3NS1hYTgzLTQ5YmU2ZjQwZWE0ZC5qcGc=",
    year: "2022",
    starring: [
      "Sam Worthington",
      "Zoe Saldaña",
      "Sigourney Weaver",
      "Stephen Lang",
    ],
    directedBy: ["James Cameron"],
  },
  {
    id: 2,
    title: "Avatar",
    url: "https://www.rottentomatoes.com/m/avatar",
    img: "https://resizing.flixster.com/uyLuq9KDv869FTTF_dqB6nZwtYI=/fit-in/180x240/v2/https://resizing.flixster.com/f0bXqQUdQ0m6fyqZjI1OXSEia9E=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzEzYmY3ZmZiLWMzYjEtNDQxMy05NTAxLTc2YTRlNmE3NWY2MC5qcGc=",
    year: "2009",
    starring: [
      "Sam Worthington",
      "Zoe Saldana",
      "Sigourney Weaver",
      "Stephen Lang",
    ],
    directedBy: ["James Cameron"],
  },
  {
    id: 3,
    title: "The Banshees of Inisherin",
    url: "https://www.rottentomatoes.com/m/the_banshees_of_inisherin",
    img: "https://resizing.flixster.com/38PH-W8opo0IaZfagCCFJtTq-_8=/fit-in/180x240/v2/https://resizing.flixster.com/SqYohHz5ela5G1qTZ8aKYunK2Oo=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzc4ZjI3ZDBiLTkwMDktNDVkZC1hZmI5LTJiNDdjNWRmZDVjOC5qcGc=",
    year: "2022",
    starring: [
      "Colin Farrell",
      "Brendan Gleeson",
      "Kerry Condon",
      "Barry Keoghan",
    ],
    directedBy: ["Martin McDonagh"],
  },
  {
    id: 4,
    title: "Guillermo del Toro's Pinocchio",
    url: "https://www.rottentomatoes.com/m/guillermo_del_toros_pinocchio",
    img: "https://resizing.flixster.com/Wdjp7fAcf3qHR4l5yMO0fduWoqM=/fit-in/180x240/v2/https://resizing.flixster.com/21j7kYKcSY89f0BqEBs-MUCmfkk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FiZWNkNjYzLTRkYTAtNGI2My05NmUzLWNkZmM0ZjI2NDk4Zi5qcGc=",
    year: "2022",
    starring: [
      "Gregory Mann",
      "Ewan McGregor",
      "David Bradley",
      "Tilda Swinton",
    ],
    directedBy: ["Guillermo del Toro", "Mark Gustafson"],
  },
  {
    id: 5,
    title: "The Whale",
    url: "https://www.rottentomatoes.com/m/the_whale_2022",
    img: "https://resizing.flixster.com/PDrK0zFj3N6Mg6rufovI7Phh1jc=/fit-in/180x240/v2/https://resizing.flixster.com/k4O2dPmx9brEPScWUiuFiayMHpo=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2M3ODEzY2Q4LTc4YWEtNDQ0OC1hNGQ0LTU0NGQzZWJjMzNhMy5qcGc=",
    year: "2022",
    starring: ["Brendan Fraser", "Sadie Sink", "Hong Chau", "Ty Simpkins"],
    directedBy: ["Darren Aronofsky"],
  },
  {
    id: 6,
    title: "Black Adam",
    url: "https://www.rottentomatoes.com/m/black_adam",
    img: "https://resizing.flixster.com/_HRCwQKye_EnjgRiOBpGLpIInbI=/fit-in/180x240/v2/https://resizing.flixster.com/TX2lzGvmmae21WwTHTBu48lySbM=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzYxNTg1OWIzLTFjZTAtNDRjMC1iNTM4LTlkY2FkNGVkY2MwMS5qcGc=",
    year: "2022",
    starring: ["Dwayne Johnson", "Aldis Hodge", "Noah Centineo", "Sarah Shahi"],
    directedBy: ["Jaume Collet-Serra"],
  },
  {
    id: 7,
    title: "Emily the Criminal",
    url: "https://www.rottentomatoes.com/m/emily_the_criminal",
    img: "https://resizing.flixster.com/loLSjj4yoQxRdIUP4MVQmhXObbM=/fit-in/180x240/v2/https://resizing.flixster.com/qtYisqOwDStnpo2P22PRTHC53Uk=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2NmMmQ0ZTRiLWVkOGYtNDllNS05ZjRiLWYyY2RhMjk1YzRjYi5qcGc=",
    year: "2022",
    starring: [
      "Aubrey Plaza",
      "Theo Rossi",
      "Megalyn Echikunwoke",
      "Jonathan Avigdori",
    ],
    directedBy: ["John Patton Ford"],
  },
  {
    id: 8,
    title: "Emancipation",
    url: "https://www.rottentomatoes.com/m/emancipation_2022",
    img: "https://resizing.flixster.com/UeUSIlQJ565qVZBC9O-xZVfXdYc=/fit-in/180x240/v2/https://resizing.flixster.com/NKgzUAvlmGdyEbQ4rpyhwLz0_6A=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2Q2MGQ5YWVjLWQyZmItNDMwZC1hZGYyLTRkZjMzMzBkNTQwYy5wbmc=",
    year: "2022",
    starring: ["Will Smith", "Ben Foster", "Charmaine Bingwa", "Gilbert Owuor"],
    directedBy: ["Antoine Fuqua"],
  },
  {
    id: 9,
    title: "Prisoners",
    url: "https://www.rottentomatoes.com/m/prisoners_2013",
    img: "https://resizing.flixster.com/DoghjMMg9U_KbDU42PzObtn8PeU=/fit-in/180x240/v2/https://flxt.tmsimg.com/assets/p9872448_p_v8_ab.jpg",
    year: "2013",
    starring: ["Hugh Jackman", "Jake Gyllenhaal", "Viola Davis", "Maria Bello"],
    directedBy: ["Denis Villeneuve"],
  },
  {
    id: 10,
    title: "Violent Night",
    url: "https://www.rottentomatoes.com/m/violent_night",
    img: "https://resizing.flixster.com/1dJJTLuKk3Xuse5YA7Zb29RRQdg=/fit-in/180x240/v2/https://resizing.flixster.com/nifeYuz3wPgP583Gtef3bTSwfI0=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzRjMjhmYTMwLWViM2EtNDZjYy1iMWRmLTAxNmQ3MzZiMTUyNS5qcGc=",
    year: "2022",
    starring: [
      "David Harbour",
      "John Leguizamo",
      "Alex Hassell",
      "Alexis Louder",
    ],
    directedBy: ["Tommy Wirkola"],
  },
  {
    id: 11,
    title: "The Menu",
    url: "https://www.rottentomatoes.com/m/the_menu",
    img: "https://resizing.flixster.com/paM60Yir6K6M3X5D1Bnr7ZqTTac=/fit-in/180x240/v2/https://resizing.flixster.com/ThP55y9O__xdEFFCmmJ0pDy9FeI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FlZTkwYTAyLWNkNWYtNDA0ZS04N2FhLTE0NDUwZmM0ODdiOC5qcGc=",
    year: "2022",
    starring: [
      "Ralph Fiennes",
      "Anya Taylor-Joy",
      "Nicholas Hoult",
      "Hong Chau",
    ],
    directedBy: ["Mark Mylod"],
  },
  {
    id: 12,
    title: "Bullet Train",
    url: "https://www.rottentomatoes.com/m/bullet_train_2022",
    img: "https://resizing.flixster.com/CvinnVABtVo7p-3d7rxxXdsJwiI=/fit-in/180x240/v2/https://resizing.flixster.com/0Wuqfdlk2B3QUnrB7wPlQ7c47AI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzI3OTIwZDU1LTEwNmQtNGYwZS1iNjhlLTIwNmU0MjdiYmY2MS5qcGc=",
    year: "2022",
    starring: [
      "Brad Pitt",
      "Joey King",
      "Aaron Taylor-Johnson",
      "Brian Tyree Henry",
    ],
    directedBy: ["David Leitch"],
  },
  {
    id: 13,
    title: "Amsterdam",
    url: "https://www.rottentomatoes.com/m/amsterdam_2022",
    img: "https://resizing.flixster.com/tWtcl95jprSrH4CJQfr5MGEhp64=/fit-in/180x240/v2/https://resizing.flixster.com/DFCWBFU_12mF8KKc2hXVJVfoqFs=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2IzMDFmOGM4LTFmYWEtNDA5OC05MzVhLWVkMDkxYjM3ZWI0NS5qcGc=",
    year: "2022",
    starring: [
      "Christian Bale",
      "Margot Robbie",
      "John David Washington",
      "Chris Rock",
    ],
    directedBy: ["David O. Russell"],
  },
  {
    id: 14,
    title: "The Fabelmans",
    url: "https://www.rottentomatoes.com/m/the_fabelmans",
    img: "https://resizing.flixster.com/H_9Itn_haLI0RzlXf9wRdv6wdi4=/fit-in/180x240/v2/https://resizing.flixster.com/sHWlKXB2LojbyFEGXuLICWYopdI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzA3Y2Y3MTk3LWZkMWUtNGNjNS04YzY0LWI0YjNlNDNmYTRhNC5qcGc=",
    year: "2022",
    starring: [
      "Michelle Williams",
      "Paul Dano",
      "Seth Rogen",
      "Gabriel LaBelle",
    ],
    directedBy: ["Steven Spielberg"],
  },
  {
    id: 15,
    title: "Jurassic Punk",
    url: "https://www.rottentomatoes.com/m/jurassic_punk",
    img: "https://resizing.flixster.com/ZOYDAWI94hlDCdhfteX_7CHZ--o=/fit-in/180x240/v2/https://resizing.flixster.com/Ka1kH5xfXoutHTTzbG3PktojAnc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzE1NzAxZDg3LTQ4OTEtNDM3OC1hM2YzLWNjZTNhODQ2ZTM3ZS5qcGc=",
    year: "2022",
    starring: [
      'Steve "Spaz" Williams',
      "Phil Tippett",
      "Robert Patrick",
      "Jamie Hyneman",
    ],
    directedBy: ["Scott Leberecht"],
  },
  {
    id: 16,
    title: "Black Panther: Wakanda Forever",
    url: "https://www.rottentomatoes.com/m/black_panther_wakanda_forever",
    img: "https://resizing.flixster.com/459b5JEuNlUflNrebS0a807KMYI=/fit-in/180x240/v2/https://resizing.flixster.com/QJkeIM6LIvwmRGiLKrNBcpZIk8M=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzAwYzExZjlmLWJlODQtNDY4Mi1iNDhkLWU2YWNmMGIyMDgwMi5qcGc=",
    year: "2022",
    starring: [
      "Letitia Wright",
      "Angela Bassett",
      "Lupita Nyong'o",
      "Tenoch Huerta",
    ],
    directedBy: ["Ryan Coogler"],
  },
  {
    id: 17,
    title: "Troll",
    url: "https://www.rottentomatoes.com/m/troll_2022",
    img: "https://resizing.flixster.com/F0cE-QeuW5g7wlBhWtWjJhYpD7A=/fit-in/180x240/v2/https://resizing.flixster.com/ot7jNKIJPa0svcG5Hcuqmkx_WsU=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzJiZWI4N2Y4LTgwZTctNGEwZS05ZmMxLWQ3M2QzYTllM2IwMy5qcGc=",
    year: "2022",
    starring: [
      "Ine Marie Wilmann",
      "Kim S. Falck-Jørgensen",
      "Mads Sjøgård Pettersen",
      "Gard B. Eidsvold",
    ],
    directedBy: ["Roar Uthaug"],
  },
  {
    id: 18,
    title: "The Quiet Girl",
    url: "https://www.rottentomatoes.com/m/the_quiet_girl",
    img: "https://resizing.flixster.com/pBdaRRPCtM4XAtRZSKeulwOFGFE=/fit-in/180x240/v2/https://resizing.flixster.com/_6p5XUDwq1MBH_OZtlIdfO60RXM=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FkODdlMTZmLTMzZjYtNDg2NC1iN2U1LTgyYTkwNGEwZDJmMC5qcGc=",
    year: "2022",
    starring: [
      "Catherine Clinch",
      "Carrie Crowley",
      "Andrew Bennett",
      "Michael Patric",
    ],
    directedBy: ["Colm Bairead"],
  },
  {
    id: 19,
    title: "Spirited",
    url: "https://www.rottentomatoes.com/m/spirited",
    img: "https://resizing.flixster.com/WllTPtrc_rRE3MS-5G6gRY_3FAs=/fit-in/180x240/v2/https://resizing.flixster.com/s6PvcgVhH04SrT5Fy8TfoGdxQMs=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2U0MWNhYmQzLWQ0NzItNGMzMS04OTM2LTg4NGI0YWZiNThiYS5qcGc=",
    year: "2022",
    starring: [
      "Will Ferrell",
      "Ryan Reynolds",
      "Octavia Spencer",
      "Patrick Page",
    ],
    directedBy: ["Sean Anders"],
  },
  {
    id: 20,
    title: "Bones and All",
    url: "https://www.rottentomatoes.com/m/bones_and_all",
    img: "https://resizing.flixster.com/K-ULkuemS7wi7HLjLEQUDHYkNZY=/fit-in/180x240/v2/https://resizing.flixster.com/Gh7qG8R8GIHpmPfCURKywhQgBFU=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2YzOGQ3NTUyLWIyMzctNGEwMy1iMjYyLWFlNTYzOWZjMmNkOS5qcGc=",
    year: "2022",
    starring: [
      "Taylor Russell",
      "Timothée Chalamet",
      "Michael Stuhlbarg",
      "André Holland",
    ],
    directedBy: ["Luca Guadagnino"],
  },
  {
    id: 21,
    title: "Empire of Light",
    url: "https://www.rottentomatoes.com/m/empire_of_light",
    img: "https://resizing.flixster.com/ZuCzmzKakKrlf-t1B909KdP3D2E=/fit-in/180x240/v2/https://resizing.flixster.com/zHNGBsas3_aRsBnBAlLRdxdg3lA=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2JlNTZkMzljLTQ2ZDctNGQ2Yy04ZGNlLWU4ZTNjNGZkZmQxNi5qcGc=",
    year: "2022",
    starring: ["Olivia Colman", "Micheal Ward", "Colin Firth", "Toby Jones"],
    directedBy: ["Sam Mendes"],
  },
  {
    id: 22,
    title: "Glass Onion: A Knives Out Mystery",
    url: "https://www.rottentomatoes.com/m/glass_onion_a_knives_out_mystery",
    img: "https://resizing.flixster.com/RYcOPgW8hdQ09-9LDMJxI-gZr-c=/fit-in/180x240/v2/https://resizing.flixster.com/Mtg-vEUajN8oamKcLLI7hZT-Rhs=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2FhYTcxNzNkLTExYzItNDk1NC1iNDNmLWViMDRlYjg5NzliNC5qcGc=",
    year: "2022",
    starring: ["Daniel Craig", "Edward Norton", "Dave Bautista", "Kate Hudson"],
    directedBy: ["Rian Johnson"],
  },
  {
    id: 23,
    title: "Stutz",
    url: "https://www.rottentomatoes.com/m/stutz",
    img: "https://resizing.flixster.com/wohbS8judTPvnbzcM7tVZmy4Fz4=/fit-in/180x240/v2/https://resizing.flixster.com/Px-SYE8csbAnU0fHcGOuGGh0Ll4=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2YwYjRjMmVmLTM3NWItNGVkZi05ZDY3LTJhNTg3OTJmMDUwZC5qcGc=",
    year: "2022",
    starring: ["Phil Stutz", "Jonah Hill"],
    directedBy: ["Jonah Hill"],
  },
  {
    id: 24,
    title: "The Woman King",
    url: "https://www.rottentomatoes.com/m/the_woman_king",
    img: "https://resizing.flixster.com/XMmhnBXRpZcV5ux1G8DwsSDiG2M=/fit-in/180x240/v2/https://resizing.flixster.com/BwXaeEZJNNzzduc8EaebjKl2aGc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzY4YTIwMGI3LTk1YjUtNDY1ZC1hYmMyLTIwM2UwZjc2OTY4Mi5qcGc=",
    year: "2022",
    starring: ["Viola Davis", "Thuso Mbedu", "Lashana Lynch", "Sheila Atim"],
    directedBy: ["Gina Prince-Bythewood"],
  },
  {
    id: 25,
    title: "Everything Everywhere All at Once",
    url: "https://www.rottentomatoes.com/m/everything_everywhere_all_at_once",
    img: "https://resizing.flixster.com/YEtJo5X13brZTogcU54WYk-lEbI=/fit-in/180x240/v2/https://resizing.flixster.com/mx-agGjjsUK1QMyuv3AJhHI3hgo=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzA3ZjU2MGU1LWMxODItNDlkMC1hYzJhLTY2YzMwOGZkMDhiZi5qcGc=",
    year: "2022",
    starring: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "James Hong"],
    directedBy: ["Daniel Kwan", "Daniel Scheinert"],
  },
  {
    id: 26,
    title: "Who Killed Santa? A Murderville Murder Mystery",
    url: "https://www.rottentomatoes.com/m/who_killed_santa_a_murderville_murder_mystery",
    img: "https://resizing.flixster.com/HDmDcS-tPCpdsc9VhSWh5X2ZkaA=/fit-in/180x240/v2/https://resizing.flixster.com/M3o16Ga0mASLHeBIbIKnFHnC5Sw=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2UzMTk3NDlkLWU0Y2EtNGM4ZS05OTNkLTYwMWQ0MDg4ZjM3MC5qcGc=",
    year: "2022",
    starring: ["Will Arnett", "Jason Bateman", "Maya Rudolph", "Eliza Coupe"],
    directedBy: ["Laura Murphy"],
  },
  {
    id: 27,
    title: "Pinocchio",
    url: "https://www.rottentomatoes.com/m/pinocchio_2022",
    img: "https://resizing.flixster.com/qVp6o38ysIUoGvg40Bn92JKqiN8=/fit-in/180x240/v2/https://resizing.flixster.com/KdI1Slb8j9ReUCdEQonDOCKPI9o=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2RlMzg0NDBjLTIxZjAtNGVkOC05MDAxLTI3M2IxMzE1MTUyYi5qcGc=",
    year: "2022",
    starring: [
      "Tom Hanks",
      "Benjamin Evan Ainsworth",
      "Cynthia Erivo",
      "Joseph Gordon-Levitt",
    ],
    directedBy: ["Robert Zemeckis"],
  },
  {
    id: 28,
    title: "Don't Worry Darling",
    url: "https://www.rottentomatoes.com/m/dont_worry_darling",
    img: "https://resizing.flixster.com/yfRxmeFA5-rad8yCZqOHSvoqLWg=/fit-in/180x240/v2/https://resizing.flixster.com/dX60R1nXMJfzdK6j2at14tigHPc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2JiMmM0MTExLWYwMTUtNDBhYy1hZmY5LTQ3Yjc1ODM1ZDA4OS5qcGc=",
    year: "2022",
    starring: ["Florence Pugh", "Harry Styles", "Olivia Wilde", "Gemma Chan"],
    directedBy: ["Olivia Wilde"],
  },
  {
    id: 29,
    title: "Strange World",
    url: "https://www.rottentomatoes.com/m/strange_world",
    img: "https://resizing.flixster.com/zc0yzOnBKobgvtK2dBnFxxyh3so=/fit-in/180x240/v2/https://resizing.flixster.com/2xMkNqbnCcVFU3sEAhAblUFRJa8=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzk5ZjM1MDZlLWU4ZWEtNDRjMi05Y2ViLTk4ZmY1YmQ3NjU2MS5qcGc=",
    year: "2022",
    starring: [
      "Jake Gyllenhaal",
      "Alan Tudyk",
      "Dennis Quaid",
      "Jaboukie Young-White",
    ],
    directedBy: ["Don Hall", "Qui Nguyen"],
  },
  {
    id: 30,
    title: "God's Crooked Lines",
    url: "https://www.rottentomatoes.com/m/gods_crooked_lines",
    img: "https://resizing.flixster.com/SRMaQPG5hr7bTMKXvi_te9DOAxI=/fit-in/180x240/v2/https://resizing.flixster.com/30ysEwi1SZLok3FOBHSRWCRXXNI=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzUxNzM5NWExLTZhZDQtNDVjNy04Mzk2LTdjZjNhMTJlZWZmNi5qcGc=",
    year: "2022",
    starring: [
      "Bárbara Lennie",
      "Eduard Fernández",
      "Loreto Mauleón",
      "Pablo Derqui",
    ],
    directedBy: ["Oriol Paulo"],
  },
];
