export const Trailers = [
  { video: "https://youtu.be/gFc9mh4y8NA", id: 1 },
  { video: "https://youtu.be/058s3smFXx0", id: 2 },
  { video: "https://youtu.be/KAhM85BOC6Y", id: 3 },
  { video: "https://youtu.be/FR9iLjOubWc", id: 4 },
  { video: "https://youtu.be/1LEsILmgbLk", id: 5 },
  { video: "https://youtu.be/Q73UhUTs6y0", id: 6 },
  { video: "https://youtu.be/jPlwnzFyPjM", id: 7 },
  { video: "https://youtu.be/gaQJd7qgz80", id: 8 },
  { video: "https://youtu.be/AaeEoLddBJU", id: 9 },
  { video: "https://youtu.be/JHQSRvAf8kI", id: 10 },
  { video: "https://youtu.be/hdbUNuaP9rE", id: 11 },
  { video: "https://youtu.be/bRdkRQzcrrc", id: 12 },
  { video: "https://youtu.be/iCd3oLrcz8U", id: 13 },
  { video: "https://youtu.be/DrTnNN4VooQ", id: 14 },
  { video: "https://youtu.be/seQbgcZ09xw", id: 15 },
  { video: "https://youtu.be/CdkxJ8BD0EI", id: 16 },
  { video: "https://youtu.be/3nPz-uRO9HI", id: 17 },
  { video: "https://youtu.be/ru0PmaWoHxM", id: 18 },
  { video: "https://youtu.be/JaRLlh8Pw5A", id: 19 },
  { video: "https://youtu.be/D70Wk6hd3Sc", id: 20 },
  { video: "https://youtu.be/CVwIElayaK8", id: 21 },
  { video: "https://youtu.be/lJCEUXVV_h4", id: 22 },
  { video: "https://youtu.be/05QRkEcWVAs", id: 23 },
  { video: "https://youtu.be/7AXrqIB2yVM", id: 24 },
  { video: "https://youtu.be/s_i5yJN7EKM", id: 25 },
];
